sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#    定义OSS相关配置
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t6fq9nRwt8FVYS9bpS6
    access-key-secret: B3mtT8a6aNx45W3xV1MVNrv1yn0f9t
    bucket-name: javaweb144
